app/controllers/ShopController.php
<?php

namespace app\controllers;

use app\models\GadgetsFilterForm;
use Yii;
use yii\easyii\modules\catalog\api\Catalog;
use yii\web\NotFoundHttpException;

class ShopController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionCat($slug)
    {
        $filterForm = new GadgetsFilterForm();
        $cat = Catalog::cat($slug);

        if(!$cat){
            throw new NotFoundHttpException('Shop category not found.');
        }
        $filters = null;
        if($filterForm->load(Yii::$app->request->get()) && $filterForm->validate()) {
            $filters = $filterForm->parse();
        }

        return $this->render('cat', [
            'cat' => $cat,
            'items' => $cat->items([
                'pagination' => ['pageSize' => 2],
                'filters' => $filters
            ]),
            'filterForm' => $filterForm
        ]);
    }

    public function actionSearch($text)
    {
        $text = filter_var($text, FILTER_SANITIZE_STRING);

        return $this->render('search', [
            'text' => $text,
            'items' => Catalog::items([
                'where' => ['or', ['like', 'title', $text], ['like', 'description', $text]],
            ])
        ]);
    }

    public function actionView($slug)
    {
        $item = Catalog::get($slug);
        if(!$item){
            throw new NotFoundHttpException('Item not found.');
        }

        return $this->render('view', [
            'item' => $item,
            'addToCartForm' => new \app\models\AddToCartForm()
        ]);
    }
}

app/controllers/ShopcartController.php
<?php

namespace app\controllers;

use app\models\AddToCartForm;
use Yii;
use yii\easyii\modules\catalog\api\Catalog;
use yii\easyii\modules\shopcart\api\Shopcart;
use yii\web\NotFoundHttpException;

class ShopcartController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index', [
            'goods' => Shopcart::goods()
        ]);
    }

    public function actionSuccess()
    {
        return $this->render('success');
    }

    public function actionAdd($id)
    {
        $item = Catalog::get($id);

        if(!$item){
            throw new NotFoundHttpException('Item not found');
        }

        $form = new AddToCartForm();
        $success = 0;
        if($form->load(Yii::$app->request->post()) && $form->validate()){
            $response = Shopcart::add($item->id, $form->count, $form->color);
            $success = $response['result'] == 'success' ? 1 : 0;
        }

        return $this->redirect(Yii::$app->request->referrer.'?'.AddToCartForm::SUCCESS_VAR.'='.$success);
    }

    public function actionRemove($id)
    {
        Shopcart::remove($id);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionUpdate()
    {
        Shopcart::update(Yii::$app->request->post('Good'));
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionOrder($id, $token)
    {
        $order = Shopcart::order($id);
        if(!$order || $order->access_token != $token){
            throw new NotFoundHttpException('Order not found');
        }

        return $this->render('order', ['order' => $order]);
    }

}

app/views/shopcart/index.php
<?php
use yii\easyii\modules\page\api\Page;
use yii\easyii\modules\shopcart\api\Shopcart;
use yii\helpers\Html;
use yii\helpers\Url;

$page = Page::get('page-shopcart');

$this->title = $page->seo('title', $page->model->title);
$this->params['breadcrumbs'][] = $page->model->title;
?>
<h1><?= $page->seo('h1', $page->title) ?></h1>

<br/>

<?php if(count($goods)) : ?>
    <div class="row">
        <div class="col-md-6">
            <?= Html::beginForm(['/shopcart/update'])?>
            <table class="table">
                <thead>
                <tr>
                    <th>Item</th>
                    <th width="100">Quantity</th>
                    <th width="120">Unit Price</th>
                    <th width="100">Total</th>
                    <th width="30"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($goods as $good) : ?>
                    <tr>
                        <td>
                            <?= Html::a($good->item->title, ['/shop/view', 'slug' => $good->item->slug]) ?>
                            <?= $good->options ? "($good->options)" : '' ?>
                        </td>
                        <td><?= Html::textInput("Good[$good->id]", $good->count, ['class' => 'form-control input-sm']) ?></td>
                        <td>
                            <?php if($good->discount) : ?>
                                <del class="text-muted "><small><?= $good->item->oldPrice ?></small></del>
                            <?php endif; ?>
                            <?= $good->price ?>
                        </td>
                        <td><?= $good->price * $good->count ?></td>
                        <th><?= Html::a('<i class="glyphicon glyphicon-trash text-danger"></i>', ['/shopcart/remove', 'id' => $good->id], ['title' => 'Remove item']) ?></th>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td colspan="5" class="text-right">
                        <h3>Total: <?= Shopcart::cost() ?>$</h3>
                    </td>
                </tr>
                </tbody>
            </table>
            <?= Html::submitButton('<i class="glyphicon glyphicon-refresh"></i> Update', ['class' => 'btn btn-default pull-right']) ?>
            <?= Html::endForm()?>
        </div>
        <div class="col-md-4 col-md-offset-2">
            <h4>Checkout</h4>
            <div class="well well">
                <?= Shopcart::form(['successUrl' => Url::to('/shopcart/success')])?>
            </div>
        </div>
    </div>
<?php else : ?>
    <p>Shopping cart is empty</p>
<?php endif; ?>

app/views/shopcart/order.php
<?php
use yii\helpers\Html;

$this->title = 'Order details';
?>
<h1>Order #<?= $order->id ?></h1>

<div class="well well-sm">Status: <b><?= $order->status ?></b></div>

<table class="table">
    <thead>
    <tr>
        <th>Item</th>
        <th width="100">Quantity</th>
        <th width="120">Unit Price</th>
        <th width="100">Total</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($order->goods as $good) : ?>
        <tr>
            <td>
                <?= Html::a($good->item->title, ['/shop/view', 'slug' => $good->item->slug]) ?>
                <?= $good->options ? "($good->options)" : '' ?>
            </td>
            <td><?= $good->count ?></td>
            <td>
                <?php if($good->discount) : ?>
                    <del class="text-muted "><small><?= $good->item->oldPrice ?></small></del>
                <?php endif; ?>
                <?= $good->price ?>
            </td>
            <td><?= $good->price * $good->count ?></td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td colspan="5" class="text-right">
            <h3>Total: <?= $order->cost ?>$</h3>
        </td>
    </tr>
    </tbody>
</table>

app/views/shopcart/success.php
<?php
use yii\easyii\modules\page\api\Page;
use yii\easyii\modules\shopcart\api\Shopcart;
use yii\helpers\Html;

$page = Page::get('page-shopcart-success');

$this->title = $page->seo('title', $page->model->title);
$this->params['breadcrumbs'][] = $page->model->title;
?>
<h1><?= $page->seo('h1', $page->title) ?></h1>

<br/>

<?= $page->text ?>